# Generated by Django 3.0.7 on 2020-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
